"""Initial migration

Revision ID: 4b970a85aa79
Revises: 
Create Date: 2026-05-16 15:57:13.691480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b970a85aa79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('goal_setting_open', sa.Date(), nullable=False),
    sa.Column('goal_setting_close', sa.Date(), nullable=False),
    sa.Column('q1_open', sa.Date(), nullable=False),
    sa.Column('q1_close', sa.Date(), nullable=False),
    sa.Column('q2_open', sa.Date(), nullable=False),
    sa.Column('q2_close', sa.Date(), nullable=False),
    sa.Column('q3_open', sa.Date(), nullable=False),
    sa.Column('q3_close', sa.Date(), nullable=False),
    sa.Column('q4_open', sa.Date(), nullable=False),
    sa.Column('q4_close', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycles_id'), 'cycles', ['id'], unique=False)
    op.create_table('thrust_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thrust_areas_id'), 'thrust_areas', ['id'], unique=False)
    op.create_index(op.f('ix_thrust_areas_name'), 'thrust_areas', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'MANAGER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'UNLOCK', 'APPROVE', 'RETURN', name='auditaction'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('thrust_area_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uom_type', sa.Enum('NUMERIC_MIN', 'NUMERIC_MAX', 'PERCENT_MIN', 'PERCENT_MAX', 'TIMELINE', 'ZERO', name='uomtype'), nullable=False),
    sa.Column('target_value', sa.Numeric(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('weightage', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'LOCKED', 'RETURNED', name='goalstatus'), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('shared_parent_id', sa.Integer(), nullable=True),
    sa.Column('is_shared_primary', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_parent_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['thrust_area_id'], ['thrust_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Enum('Q1', 'Q2', 'Q3', 'Q4', name='quarter'), nullable=False),
    sa.Column('actual_value', sa.Numeric(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'ON_TRACK', 'COMPLETED', name='achievementstatus'), nullable=False),
    sa.Column('score_percent', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'quarter', name='_goal_quarter_uc')
    )
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Enum('Q1', 'Q2', 'Q3', 'Q4', name='quarter'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'quarter', name='_checkin_goal_quarter_uc')
    )
    op.create_index(op.f('ix_checkins_id'), 'checkins', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkins_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_thrust_areas_name'), table_name='thrust_areas')
    op.drop_index(op.f('ix_thrust_areas_id'), table_name='thrust_areas')
    op.drop_table('thrust_areas')
    op.drop_index(op.f('ix_cycles_id'), table_name='cycles')
    op.drop_table('cycles')
    # ### end Alembic commands ###
